version: '3.8'

services:
  simulateur_convoyeur:
    build:
      context: .
      dockerfile: ./machine-simulator/dockerfile
    image: machine-simulator
    network_mode: host
    environment:
      MACHINE_ID: convoyeur-1
      MACHINE_TYPE: convoyeur
      BACKEND_URL: http://localhost:3000

  simulateur_imprimante:
    image: machine-simulator
    network_mode: host
    environment:
      MACHINE_ID: imprimante-1
      MACHINE_TYPE: imprimante3d
      BACKEND_URL: http://localhost:3000
